#!/bin/bash
#set -x

if [ -z "$1" ] 
then
  echo
  echo -e "\t   1  ARGUMENT ARE REQUIRED"
  echo -e "\t  MACHINE"
  echo
  exit 1
fi

MACHINE=$1

if [ "$MACHINE" = "TS10" ]
then
  
  if [ $COMPILING_NOT_CLEAN != "yes" ]
  then
    make distclean
  else
    echo "Compiling COMPILING_NOT_CLEAN activated"
  fi

  export PATH="/home/sources/TS10_PREMIUM/TS10_PACKAGES/ti-dvsdk_dm3730-evm_04_03_00_06/linux-devkit/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
  export PKG_CONFIG_PATH="/home/sources/TS10_PREMIUM/TS10_PACKAGES/ti-dvsdk_dm3730-evm_04_03_00_06/linux-devkit/arm-arago-linux-gnueabi/usr/lib/pkgconfig/"
  export PKG_CONFIG_SYSROOT_DIR="/home/sources/TS10_PREMIUM/TS10_PACKAGES/ti-dvsdk_dm3730-evm_04_03_00_06/linux-devkit/arm-arago-linux-gnueabi/"
  
  /usr/lib/qt/bin/qmake CONFIG+=maliit  
  make -j || exit 1
  make install  #It's necessary to create the folder dist with the executable file

  #create launcher file
  rm -f BtExperience_qws
  touch BtExperience_qws
  chmod +x BtExperience_qws
  echo "#!/bin/sh" >> BtExperience_qws
  echo "export TSLIB_TSDEVICE=/dev/input/touchscreen0" >> BtExperience_qws
  echo "export QWS_MOUSE_PROTO=Tslib:/dev/input/touchscreen0" >> BtExperience_qws
  echo "export QWS_DISPLAY=powervr" >> BtExperience_qws
  echo "export QT_IM_MODULE=MaliitDirect" >> BtExperience_qws
  echo "export LD_LIBRARY_PATH=/home/bticino/lib:$LD_LIBRARY_PATH" >> BtExperience_qws
  echo "export POINTERCAL=/etc/pointercal" >> BtExperience_qws
  echo "if [ ! -e "$POINTERCAL" ]" >> BtExperience_qws
  echo "then" >> BtExperience_qws
  echo "ts_calibrate" >> BtExperience_qws
  echo "fi" >> BtExperience_qws
  echo "bin/BtExperience/BtExperience -qws &" >> BtExperience_qws

  exit 0
fi
exit 1
