#!/bin/bash
#set -x

if [ -z "$1" ] 
then
  echo
  echo -e "\t   1  ARGUMENT ARE REQUIRED"
  echo -e "\t  MACHINE"
  echo
  exit 1
fi

MACHINE=$1
POINTERCAL=/etc/pointercal

if [ "$MACHINE" = "TS10" ]
then
  
  if [ $COMPILING_NOT_CLEAN != "yes" ]
  then
    make distclean
  else
    echo "Compiling COMPILING_NOT_CLEAN activated"
  fi

  export PATH="/home/sources/TS10_PREMIUM/TS10_PACKAGES/ti-dvsdk_dm3730-evm_04_03_00_06/linux-devkit/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
  export PKG_CONFIG_PATH="/home/sources/TS10_PREMIUM/TS10_PACKAGES/ti-dvsdk_dm3730-evm_04_03_00_06/linux-devkit/arm-arago-linux-gnueabi/usr/lib/pkgconfig/"
  export PKG_CONFIG_SYSROOT_DIR="/home/sources/TS10_PREMIUM/TS10_PACKAGES/ti-dvsdk_dm3730-evm_04_03_00_06/linux-devkit/arm-arago-linux-gnueabi/"
  
  /usr/lib/qt/bin/qmake CONFIG+=maliit  
  make -j$CPU4COMPILE || exit 1
  make install || exit 1  #It's necessary to create the folder dist with the executable file

  exit 0
fi
exit 1
