#!/bin/bash
#set -x

export BTEXPERIENCE_TARGET=$BTWEB_APP_BIN_NO_STACKOPEN/BtExperience

if [ -z "$1" ] 
then
  echo
  echo -e "\t   1  ARGUMENT ARE REQUIRED"
  echo -e "\t  MACHINE"
  echo
  exit 1
fi

MACHINE=$1

# exit if recovery (test hostname)
x=`cat $TMPFS/etc/hostname`
if [[ "$x" == *"_rec" ]]
then
exit 0
fi

mkdir $BTEXPERIENCE_TARGET
rsync -a dist/arm/ $BTEXPERIENCE_TARGET || exit 1
# by now we have two copies of libcommon... use the one in stackopen
cd ${BTEXPERIENCE_TARGET}
rm libcommon.so.0
ln -s ../../lib/libcommon.so.0.0 libcommon.so.0
#symbolic link for libbtobjects.so
ln -s BtObjects/libbtobjects.so libbtobjects.so
cd -

#create launcher file
echo "#!/bin/sh

trap \"killall BtExperience; trap SIGTERM; trap SIGUSR1; trap SIGUSR2; exit 0\" SIGTERM
trap \"killall -SIGUSR1 BtExperience; wait\" SIGUSR1
trap \"killall -SIGUSR2 BtExperience; wait\" SIGUSR2

export TSLIB_TSDEVICE=/dev/input/touchscreen0
export QWS_MOUSE_PROTO=Tslib:/dev/input/touchscreen0
export QWS_DISPLAY=powervr
export QT_IM_MODULE=MaliitDirect
export LD_LIBRARY_PATH=/home/bticino/lib:
export TSLIB_CALIBFILE=/home/bticino/cfg/extra/pointercal
export POINTERCAL=\$TSLIB_CALIBFILE
[ ! -e \$TSLIB_CALIBFILE ] && ts_calibrate
bin/BtExperience/BtExperience -qws -noswcursor &


wait" > BtExperience_qws

cp BtExperience_qws $BTWEB_APP_BIN_NO_STACKOPEN

exit 0
